import {STORAGE_KEY,fields,uid,today,createState,validateState,makeRecord,monthRecords,monthCounts,recordLabel,exerciseHistory,exerciseSummary,buildExercise,deleteType} from './movement-core.mjs';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,loadError='',month=today().slice(0,7),sportFilter='',selectedDate='',draft=null,returnTo='home',lastFocus=null;
try{const raw=localStorage.getItem(STORAGE_KEY);state=raw?validateState(JSON.parse(raw)):createState();}catch(e){state=createState();loadError='本地数据无法读取，已暂停保存以保护原数据。请先导出原始数据，再导入有效备份。';}
const app=$('#app'),sheetRoot=$('#sheet-root');
const icons={strength:'<path d="M4 10v8m4-11v14m16-11v8m-4-11v14M8 14h12M2 12v4m24-4v4"/>',dance:'<circle cx="17" cy="5" r="2"/><path d="m7 8 7 3 7-3m-7 3-3 7-6 5m8-9 5 5 5 1"/>',walk:'<path d="m8 5 4 7-3 7c-1 3 1 5 4 5h9v-4l-6-3-1-9M7 4l4-1"/>',other:'<path d="M14 5v18M5 14h18"/>',normal:'<circle cx="14" cy="14" r="9"/><path d="M14 9v10M9 14h10"/>'};
const svg=k=>`<svg viewBox="0 0 28 28" aria-hidden="true">${icons[k]||icons.normal}</svg>`;
const settingsIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="m9 3 6 0 1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1Z"/></svg>';
const dateText=d=>{const [y,m,day]=d.split('-').map(Number);return `${m}月${day}日`;};
const fullDate=d=>`${d.slice(0,4)}年${dateText(d)}`;
const typeById=id=>state.types.find(t=>t.id===id);
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2400);}
function commit(next){try{if(loadError)throw new Error(loadError);validateState(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));state=next;return true;}catch(e){toast(e.message.includes('quota')?'存储空间不足，请导出备份后清理空间。':e.message);return false;}}
function change(fn){const next=structuredClone(state);fn(next);return commit(next);}
function go(route){location.hash=route;}
function frame(title,body,{back=null,action='',tab=''}={}){app.innerHTML=`<main class="app-shell">${back?`<a class="back-button" href="#${back}">‹ 返回</a>`:''}<header class="topbar"><h1>${esc(title)}</h1>${action}</header>${loadError?`<p class="notice">${esc(loadError)}</p>`:''}${body}</main>${tab?`<nav class="bottom-nav" aria-label="主导航"><a href="#home" class="${tab==='home'?'active':''}" ${tab==='home'?'aria-current="page"':''}><span class="nav-mark" aria-hidden="true">＋</span>记录</a><a href="#history" class="${tab==='history'?'active':''}" ${tab==='history'?'aria-current="page"':''}><span class="nav-mark" aria-hidden="true">≡</span>历史</a></nav>`:''}`;}
function input(key,value='',required=false){const [label,type,unit]=fields[key]||[key,key==='date'?'date':'text',''];const title=key==='date'?'日期':label;return `<label class="field"><span>${esc(title)}</span><div class="input-wrap">${type==='textarea'?`<textarea name="${key}" maxlength="5000" placeholder="选填">${esc(value)}</textarea>`:`<input name="${key}" aria-label="${esc(title)}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?`min="0" step="${key==='steps'?'1':'any'}" inputmode="decimal"`:''} ${type==='text'?'maxlength="100"':''} class="${unit?'with-unit':''}" ${required?'':'placeholder="选填"'}>${unit?`<span class="unit">${unit}</span>`:''}`}</div></label>`;}
function recordRow(r){return `<a class="activity-row" href="#detail/${r.id}"><time datetime="${r.date}" aria-label="${fullDate(r.date)}">${r.date.replaceAll('-','')}</time><span class="activity-name">${esc(recordLabel(state,r))}</span><span class="chevron" aria-hidden="true">›</span></a>`;}
function home(){const recent=[...state.records].sort((a,b)=>b.date.localeCompare(a.date)||(b.createdAt||'').localeCompare(a.createdAt||'')).slice(0,3);frame('运动记录',`<p class="subtle home-date">${fullDate(today())} · ${['星期日','星期一','星期二','星期三','星期四','星期五','星期六'][new Date().getDay()]}</p><div class="sport-grid">${state.homeIds.map(id=>{const t=typeById(id);return `<button class="sport-tile" data-new="${esc(id)}">${svg(t.id==='walk'?'walk':t.kind)}<span class="arrow" aria-hidden="true">↗</span><strong>${esc(t.name)}</strong></button>`;}).join('')}</div><div class="section-title"><h2>最近记录</h2><a class="text-button" href="#history">查看全部 ›</a></div>${recent.length?`<div class="activity-list">${recent.map(recordRow).join('')}</div>`:'<p class="empty">还没有记录<br>点击上方运动，记下这一次。</p>'}`,{tab:'home',action:`<a class="icon-button" href="#settings" aria-label="设置">${settingsIcon}</a>`});}
function startRecord(id,existing=null){const t=typeById(id);draft=existing?structuredClone(existing):makeRecord(t,today());returnTo=existing?`detail/${existing.id}`:'home';if(location.hash===`#record/${id}`)render();else go(`record/${id}`);}
function recordPage(id){const t=typeById(id);if(!t)return go('home');if(!draft||draft.typeId!==id)draft=makeRecord(t,today());const keys=t.fields;frame(t.name,`<p class="subtle page-intro">${t.kind==='other'?'填写运动名称，其余信息可以留空。':'只记日期也可以，其余信息按需填写。'}</p><form id="record-form">${t.kind==='other'?`<label class="field"><span>运动名称 · 选填</span><input name="sportName" maxlength="100" placeholder="例如：游泳、爬山、骑车" value="${esc(draft.name===t.name?'':draft.name)}"></label>`:''}${input('date',draft.date,true)}<div class="field-grid">${keys.filter(k=>k!=='notes').map(k=>input(k,draft.values[k])).join('')}</div>${t.kind==='strength'?`<div class="section-title"><h2>训练动作</h2><span class="subtle">选填</span></div><div id="draft-exercises">${draft.exercises.map((e,i)=>`<div class="exercise-card"><div><strong>${esc(e.name)}</strong><span class="subtle">${esc(exerciseSummary(e))}</span></div><div><button type="button" class="small-button" data-edit-exercise="${i}" aria-label="编辑${esc(e.name)}">编辑</button><button type="button" class="small-button" data-remove-exercise="${i}" aria-label="移除${esc(e.name)}">×</button></div></div>`).join('')}</div><button type="button" class="add-action" data-action="pick-exercise">＋ 添加动作</button>`:''}${keys.includes('notes')?input('notes',draft.values.notes):''}<div class="save-bar"><button class="primary" type="submit">保存</button></div></form>`,{back:returnTo});$('#record-form').addEventListener('submit',e=>{e.preventDefault();captureDraft();const next=structuredClone(state);const index=next.records.findIndex(r=>r.id===draft.id);if(index<0)next.records.push(draft);else next.records[index]=draft;if(commit(next)){draft=null;toast('已保存');go(index<0?'home':returnTo);}});}
function captureDraft(){const form=$('#record-form');if(!form||!draft)return;const data=new FormData(form),t=typeById(draft.typeId);draft.date=data.get('date');if(t.kind==='other')draft.name=String(data.get('sportName')||'').trim()||t.name;for(const key of t.fields){const v=data.get(key);if(v==null||v==='')delete draft.values[key];else draft.values[key]=['notes','startTime'].includes(key)?String(v):Number(v);}}
function history(){
 if(sportFilter&&!typeById(sportFilter))sportFilter='';
 const allRecords=monthRecords(state,month),rs=allRecords.filter(r=>!sportFilter||r.typeId===sportFilter),counts=monthCounts(state,month);
 const name=sportFilter?typeById(sportFilter).name:'运动';
 const dayRecords=selectedDate?rs.filter(r=>r.date===selectedDate):[];
 frame('历史',`<div class="month-switch"><button data-month="-1" aria-label="上一个月">‹</button><span>${Number(month.slice(0,4))}年${Number(month.slice(5))}月</span><button data-month="1" aria-label="下一个月">›</button></div>

 <section class="month-summary"><h2>${month===today().slice(0,7)?'本月':'当月'}运动 <b>${allRecords.length}</b> 次</h2>${counts.length?counts.map(c=>`<div class="count-row"><span>${esc(c.name)}</span><span>${c.count}</span></div>`).join(''):''}${!allRecords.length?'<p class="subtle">这个月还没有运动记录</p>':''}</section>
 ${calendar(rs)}
 <div class="sport-filters" role="group" aria-label="按运动筛选">${[{id:'',name:'全部'},...state.types].map(t=>`<button data-filter="${esc(t.id)}" aria-pressed="${sportFilter===t.id}">${esc(t.name)}</button>`).join('')}</div>
 ${selectedDate?`<section class="selected-day" aria-label="当天记录"><div class="selected-day-heading"><h2>${dateText(selectedDate)} · ${dayRecords.length}次${sportFilter?' '+esc(name):'运动'}</h2><button class="text-button" data-action="clear-date" aria-label="关闭当天记录">关闭</button></div>${dayRecords.length?dayRecords.map(r=>`<a class="activity-row" href="#detail/${r.id}"><span class="activity-name">${esc(recordLabel(state,r))}</span><span class="chevron" aria-hidden="true">›</span></a>`).join(''):`<p class="subtle">这一天没有${sportFilter?esc(name):'运动'}记录。</p>`}</section>`:''}
 <section class="monthly-records"><div class="section-title"><h2>当月${sportFilter?esc(name):''}记录</h2></div>${rs.length?`<div class="activity-list">${rs.map(recordRow).join('')}</div>`:'<p class="empty">这个月的记录会显示在这里。</p>'}</section>
 <a class="library-entry" href="#library"><span>力量训练动作库</span><span class="chevron">›</span></a>`,{tab:'history'});
}
function refreshHistory(selector){const y=window.scrollY;history();$(selector)?.focus({preventScroll:true});window.scrollTo(0,y);}

function calendar(rs){
 const [y,m]=month.split('-').map(Number),offset=new Date(y,m-1,1).getDay(),total=new Date(y,m,0).getDate();
 const counts=new Map();for(const r of rs)counts.set(r.date,(counts.get(r.date)||0)+1);
 return `<div class="calendar" aria-label="运动月历">${['日','一','二','三','四','五','六'].map((w,i)=>`<div class="weekday ${i===0||i===6?'weekend':''}">${w}</div>`).join('')}${'<div class="calendar-spacer" aria-hidden="true"></div>'.repeat(offset)}${Array.from({length:total},(_,i)=>{
  const d=`${month}-${String(i+1).padStart(2,'0')}`,count=counts.get(d)||0,weekend=(offset+i)%7===0||(offset+i)%7===6;
  return `<button type="button" data-date="${d}" aria-pressed="${selectedDate===d}" class="calendar-day ${selectedDate===d?'selected':''} ${count?'has-activity':''} ${weekend?'weekend':''}" aria-label="${fullDate(d)}，${count}次运动"><span class="day-number">${i+1}</span><span class="dots" aria-hidden="true">${'<i></i>'.repeat(count)}</span></button>`;
 }).join('')}</div>`;
}
function detail(id){const r=state.records.find(r=>r.id===id);if(!r)return go('history');const t=typeById(r.typeId);frame(r.name,`<div class="detail-block"><span>日期</span><strong>${fullDate(r.date)}</strong></div>${Object.entries(r.values).map(([key,v])=>`<div class="detail-block"><span>${fields[key][0]}</span><strong>${esc(v)}${fields[key][2]?' '+fields[key][2]:''}</strong></div>`).join('')}${t.kind==='strength'||r.exercises.length?`<div class="section-title"><h2>训练动作</h2></div>${r.exercises.length?r.exercises.map(e=>`<a class="exercise-card" href="#exercise/${esc(e.exerciseId)}"><div><strong>${esc(e.name)}</strong><span class="subtle">${esc(exerciseSummary(e))}</span></div><span class="chevron">›</span></a>`).join(''):'<p class="subtle">这次没有记录具体动作。</p>'}`:''}<div class="actions"><button class="secondary" data-edit-record="${id}">编辑记录</button><button class="danger" data-delete-record="${id}">删除记录</button></div>`,{back:'history'});}
function library(){const active=state.exercises.filter(e=>!e.deleted).sort((a,b)=>(exerciseHistory(state,b.id)[0]?.record.date||'').localeCompare(exerciseHistory(state,a.id)[0]?.record.date||''));frame('动作库',`<p class="subtle page-intro">回看每个动作，曾经做到哪里。</p>${active.length?active.map(e=>{const last=exerciseHistory(state,e.id)[0];return `<a class="library-row" href="#exercise/${e.id}"><span><strong>${esc(e.name)}</strong><span class="subtle">${last?'最近：'+fullDate(last.record.date):'尚无训练记录'}</span></span><span class="chevron">›</span></a>`;}).join(''):'<p class="empty">还没有动作<br>在这里建立，或在训练时添加。</p>'}<button class="add-action" data-action="new-library-exercise">＋ 新建动作</button>`,{back:'history'});}
function exercisePage(id){const e=state.exercises.find(e=>e.id===id),rows=exerciseHistory(state,id);if(!e&&!rows.length)return go('library');frame(e?.name||rows[0].exercise.name,`${e?.deleted?'<p class="notice">此动作已从动作库移除，过去的训练记录仍保留。</p>':''}${rows.length?rows.map(({record,exercise})=>`<a class="library-row" href="#detail/${record.id}"><span><strong>${fullDate(record.date)}</strong><span class="subtle">${esc(exerciseSummary(exercise))}</span></span><span class="chevron">›</span></a>`).join(''):'<p class="empty">还没有这个动作的训练记录。</p>'}${e&&!e.deleted?`<div class="actions"><button class="secondary" data-rename-exercise="${id}">修改名称</button><button class="danger" data-delete-library="${id}">删除动作</button></div>`:''}`,{back:'library'});}
function settings(){frame('设置',`<section class="settings-section"><h2>首页设置</h2><div class="setting-card"><a class="setting-row" href="#home-settings"><span>首页运动方块</span><span class="subtle">${state.homeCount} 个　›</span></a></div></section><section class="settings-section"><h2>运动类型管理</h2><div class="setting-card">${state.types.map(t=>`<a class="setting-row" href="#type/${t.id}"><span>${esc(t.name)}</span><span class="chevron">›</span></a>`).join('')}<a class="setting-row" href="#type/new"><span>＋ 新增普通运动</span></a></div></section><section class="settings-section"><h2>力量训练</h2><div class="setting-card"><a class="setting-row" href="#library"><span>力量训练动作库</span><span class="chevron">›</span></a></div></section><section class="settings-section"><h2>数据</h2><div class="setting-card"><button class="setting-row" data-action="export">导出 JSON 备份</button><button class="setting-row" data-action="import">导入 JSON 备份</button></div><p class="subtle">记录仅保存在当前浏览器。更换设备或清理浏览器数据前，请先导出备份。</p></section>`,{back:'home'});}
function homeSettings(){frame('首页运动',`<p class="subtle page-intro">选择 4～6 个运动，按下方顺序显示。</p><form id="home-form"><label class="field"><span>方块数量</span><select name="count" aria-label="方块数量">${[4,5,6].map(n=>`<option ${n===state.homeCount?'selected':''}>${n}</option>`).join('')}</select></label><div id="home-slots"></div><p class="subtle">运动不够时，可先在设置中新增普通运动。</p><p class="error" id="home-error" role="alert"></p><button class="primary">保存设置</button></form>`,{back:'settings'});let selection=[...state.homeIds];const slots=()=>{$('#home-slots').innerHTML=Array.from({length:Number($('#home-form select').value)},(_,i)=>`<label class="field"><span>第 ${i+1} 个运动</span><select name="slot${i}" required aria-label="第 ${i+1} 个运动"><option value="">选择运动</option>${state.types.map(t=>`<option value="${t.id}" ${selection[i]===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label>`).join('');};slots();$('#home-form select').onchange=()=>{selection=[...$('#home-slots').querySelectorAll('select')].map(s=>s.value);slots();};$('#home-form').onsubmit=e=>{e.preventDefault();const ids=[...$('#home-slots').querySelectorAll('select')].map(s=>s.value);if(new Set(ids).size!==ids.length){$('#home-error').textContent='每个方块请选择不同的运动。';return;}if(change(s=>{s.homeCount=ids.length;s.homeIds=ids;})){toast('首页设置已保存');go('home');}};}
function typePage(id){const t=id==='new'?{id:uid(),name:'',kind:'normal',fields:[]}:typeById(id);if(!t)return go('settings');frame(id==='new'?'新增运动':'调整运动',`<form id="type-form"><label class="field"><span>运动名称</span><input name="name" aria-label="运动名称" value="${esc(t.name)}" required maxlength="100" placeholder="例如：骑车"></label>${t.kind!=='strength'?`<div class="section-title"><h2>可记录字段</h2><span class="subtle">均为选填</span></div>${Object.entries(fields).map(([k,[name]])=>`<label class="check-row"><input type="checkbox" name="fields" value="${k}" ${t.fields.includes(k)?'checked':''}>${name}</label>`).join('')}`:'<p class="subtle">力量训练保留时长、备注和训练动作。</p>'}<p class="error" id="type-error" role="alert"></p><div class="save-bar"><button class="primary">保存</button></div></form>${id!=='new'&&!['strength','dance','walk','other'].includes(id)?`<button class="text-button" data-delete-type="${id}">删除运动类型</button>`:''}`,{back:'settings'});$('#type-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target),name=data.get('name').trim();if(!name||state.types.some(x=>x.id!==t.id&&x.name===name)){$('#type-error').textContent='请填写不重复的运动名称。';return;}if(change(s=>{const updated={...t,name,fields:t.kind==='strength'?t.fields:data.getAll('fields')};const index=s.types.findIndex(x=>x.id===t.id);if(index<0)s.types.push(updated);else s.types[index]=updated;})){toast('运动已保存');go('settings');}};}
function openSheet(title,body){lastFocus=document.activeElement;sheetRoot.innerHTML=`<div class="sheet-backdrop"><section class="sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="sheet-head"><h2>${esc(title)}</h2><button class="close" aria-label="关闭" data-action="close-sheet">×</button></div>${body}</section></div>`;document.body.classList.add('sheet-open');requestAnimationFrame(()=>sheetRoot.querySelector('input,button')?.focus());}
function closeSheet(){sheetRoot.innerHTML='';document.body.classList.remove('sheet-open');lastFocus?.focus();}
function pickExercise(){captureDraft();const list=state.exercises.filter(e=>!e.deleted),recent=list.filter(e=>exerciseHistory(state,e.id).length).sort((a,b)=>exerciseHistory(state,b.id)[0].record.date.localeCompare(exerciseHistory(state,a.id)[0].record.date)).slice(0,3);const row=e=>`<button class="library-row" data-choose-exercise="${e.id}"><span>${esc(e.name)}</span><span class="chevron">›</span></button>`;openSheet('添加动作',`${recent.length?`<h3>最近使用</h3>${recent.map(row).join('')}<div class="section-title"><h3>全部动作</h3></div>`:''}${list.length?list.map(row).join(''):'<p class="subtle">建立第一个动作，下次可以直接选择。</p>'}<button class="add-action" data-action="new-training-exercise">＋ 新建动作</button>`);}
function newExercise(training=false,id=null){const old=state.exercises.find(e=>e.id===id);openSheet(old?'修改动作名称':'新建动作',`<form id="exercise-name-form"><label class="field"><span>动作名称</span><input name="name" aria-label="动作名称" required maxlength="100" value="${esc(old?.name||'')}" placeholder="例如：臀推"></label><p class="error" id="exercise-name-error" role="alert"></p><button class="primary">${training?'下一步':'保存'}</button></form>`);$('#exercise-name-form').onsubmit=e=>{e.preventDefault();const name=new FormData(e.target).get('name').trim();if(!name)return;const duplicate=state.exercises.find(x=>!x.deleted&&x.name===name&&x.id!==id);if(duplicate){if(training){exerciseForm(duplicate.id);return;}$('#exercise-name-error').textContent='动作库中已有这个名称。';return;}const exercise=old?{...old,name}:{id:uid(),name};if(change(s=>{const index=s.exercises.findIndex(x=>x.id===exercise.id);if(index<0)s.exercises.push(exercise);else s.exercises[index]=exercise;})){if(training)exerciseForm(exercise.id);else {closeSheet();render();toast('动作已保存');}}};}
function exerciseForm(id,index=null){const e=state.exercises.find(e=>e.id===id),value=index===null?{}:draft.exercises[index];openSheet(e?.name||value.name,`<form id="exercise-data-form"><p class="subtle">三项均可留空。</p><div class="triple">${[['weight','重量 kg'],['setCount','组数'],['reps','次数 reps']].map(([k,label])=>`<label class="field"><span>${label}</span><input type="number" name="${k}" aria-label="${label}" min="0" ${k==='setCount'?'max="1000"':''} step="${k==='weight'?'any':'1'}" inputmode="decimal" placeholder="选填" value="${esc(value[k])}"></label>`).join('')}</div><p class="error" id="exercise-error" role="alert"></p><button class="primary">${index===null?'添加':'保存动作'}</button></form>`);$('#exercise-data-form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.target);try{const entry=buildExercise(id,e?.name||value.name,...['weight','setCount','reps'].map(k=>data.get(k)));if(index===null)draft.exercises.push(entry);else draft.exercises[index]=entry;closeSheet();recordPage(draft.typeId);}catch(error){$('#exercise-error').textContent=error.message;}};}
function confirmSheet(title,text,action){openSheet(title,`<p class="subtle">${esc(text)}</p><div class="actions"><button class="secondary" data-action="close-sheet">取消</button><button class="danger" id="confirm-action">确认</button></div>`);$('#confirm-action').onclick=()=>{if(action()!==false)closeSheet();};}
function exportData(){const data=loadError?localStorage.getItem(STORAGE_KEY):JSON.stringify(state,null,2);const url=URL.createObjectURL(new Blob([data||''],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`运动记录-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('备份已导出');}
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>10*1024*1024)throw new Error('备份文件过大，请选择 10MB 以内的 JSON 文件。');const imported=validateState(JSON.parse(await file.text()));confirmSheet('导入备份',`备份中有 ${imported.records.length} 条记录。导入将替换当前 ${state.records.length} 条记录，建议先导出当前数据。`,()=>{const previousError=loadError;loadError='';if(!commit(imported)){loadError=previousError;return false;}draft=null;render();toast('备份已导入');});}catch(error){toast(error instanceof SyntaxError?'无法读取 JSON，请检查文件格式。':error.message);}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-filter],[data-date],[data-action],[data-new],[data-month],[data-edit-record],[data-delete-record],[data-choose-exercise],[data-edit-exercise],[data-remove-exercise],[data-rename-exercise],[data-delete-library],[data-delete-type]');if(!b)return;const d=b.dataset;if(d.filter!==undefined){sportFilter=d.filter;refreshHistory(`[data-filter="${sportFilter}"]`);return;}if(d.date){selectedDate=d.date;refreshHistory(`[data-date="${selectedDate}"]`);return;}if(d.new){startRecord(d.new);return;}if(d.month){const [y,m]=month.split('-').map(Number);month=today(new Date(y,m-1+Number(d.month),1)).slice(0,7);selectedDate='';refreshHistory(`[data-month="${d.month}"]`);return;}if(d.editRecord){const r=state.records.find(r=>r.id===d.editRecord);startRecord(r.typeId,r);return;}if(d.deleteRecord){confirmSheet('删除记录','删除后无法恢复。',()=>{if(!change(s=>s.records=s.records.filter(r=>r.id!==d.deleteRecord)))return false;go('history');toast('记录已删除');});return;}if(d.chooseExercise){exerciseForm(d.chooseExercise);return;}if(d.editExercise!==undefined){captureDraft();const i=Number(d.editExercise);exerciseForm(draft.exercises[i].exerciseId,i);return;}if(d.removeExercise!==undefined){captureDraft();draft.exercises.splice(Number(d.removeExercise),1);recordPage(draft.typeId);return;}if(d.renameExercise){newExercise(false,d.renameExercise);return;}if(d.deleteLibrary){confirmSheet('删除动作','从动作库中移除。已有训练记录与动作历史会保留。',()=>{if(!change(s=>s.exercises.find(x=>x.id===d.deleteLibrary).deleted=true))return false;go('library');});return;}if(d.deleteType){confirmSheet('删除运动类型','已有记录保留原名称，月度次数将归入「其他」。',()=>{try{if(!change(s=>deleteType(s,d.deleteType)))return false;go('settings');}catch(error){toast(error.message);return false;}});return;}switch(d.action){case'clear-date':{const date=selectedDate;selectedDate='';refreshHistory(`[data-date="${date}"]`);break;}case'pick-exercise':pickExercise();break;case'new-training-exercise':newExercise(true);break;case'new-library-exercise':newExercise();break;case'close-sheet':closeSheet();break;case'export':exportData();break;case'import':$('#import-file').click();break;}});
document.addEventListener('keydown',e=>{if(!sheetRoot.children.length)return;if(e.key==='Escape'){closeSheet();return;}if(e.key==='Tab'){const nodes=[...sheetRoot.querySelectorAll('button,input,select,textarea,a[href]')].filter(n=>!n.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
function render(){const [route='home',id]=location.hash.slice(1).split('/');switch(route){case'home':case'':home();break;case'history':history();break;case'record':recordPage(id);break;case'detail':detail(id);break;case'library':library();break;case'exercise':exercisePage(id);break;case'settings':settings();break;case'home-settings':homeSettings();break;case'type':typePage(id);break;default:home();}}
window.addEventListener('hashchange',()=>{closeSheet();render();window.scrollTo(0,0);});window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY){try{state=e.newValue?validateState(JSON.parse(e.newValue)):createState();loadError='';render();}catch{toast('其他页面的数据更新无法读取，请刷新后检查。');}}});render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
